// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: proto/ingest.proto

package bitacorapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metric is one Prometheus-model sample (ADR-0006).
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type EventSubject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSubject) Reset() {
	*x = EventSubject{}
	mi := &file_proto_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubject) ProtoMessage() {}

func (x *EventSubject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubject.ProtoReflect.Descriptor instead.
func (*EventSubject) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *EventSubject) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EventSubject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventSubject) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type LogRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRef) Reset() {
	*x = LogRef{}
	mi := &file_proto_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRef) ProtoMessage() {}

func (x *LogRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRef.ProtoReflect.Descriptor instead.
func (*LogRef) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *LogRef) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *LogRef) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

// Event is a discrete, significant fact (ADR-0006).
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TsMs          int64                  `protobuf:"varint,2,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	TsReceivedMs  int64                  `protobuf:"varint,3,opt,name=ts_received_ms,json=tsReceivedMs,proto3" json:"ts_received_ms,omitempty"`
	HostId        string                 `protobuf:"bytes,4,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Severity      string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	Title         string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Subject       *EventSubject          `protobuf:"bytes,9,opt,name=subject,proto3" json:"subject,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,10,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fingerprint   string                 `protobuf:"bytes,11,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	LogRefs       []*LogRef              `protobuf:"bytes,12,rep,name=log_refs,json=logRefs,proto3" json:"log_refs,omitempty"`
	Schema        int32                  `protobuf:"varint,13,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *Event) GetTsReceivedMs() int64 {
	if x != nil {
		return x.TsReceivedMs
	}
	return 0
}

func (x *Event) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetSubject() *EventSubject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Event) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *Event) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Event) GetLogRefs() []*LogRef {
	if x != nil {
		return x.LogRefs
	}
	return nil
}

func (x *Event) GetSchema() int32 {
	if x != nil {
		return x.Schema
	}
	return 0
}

// LogLine is one raw log line (ADR-0006).
type LogLine struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TsMs            int64                  `protobuf:"varint,1,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	HostId          string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Source          string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Stream          string                 `protobuf:"bytes,4,opt,name=stream,proto3" json:"stream,omitempty"`
	UnitOrContainer string                 `protobuf:"bytes,5,opt,name=unit_or_container,json=unitOrContainer,proto3" json:"unit_or_container,omitempty"`
	Level           string                 `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
	Pid             int32                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	Message         string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_proto_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *LogLine) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *LogLine) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *LogLine) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogLine) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogLine) GetUnitOrContainer() string {
	if x != nil {
		return x.UnitOrContainer
	}
	return ""
}

func (x *LogLine) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLine) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// InventoryItem is one entry of an Inventory snapshot (ADR-0015), e.g. one
// share, one VM, one user.
type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,3,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_proto_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *InventoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InventoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InventoryItem) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

// Inventory is a declarative snapshot of list-shaped data — shares, VMs,
// users, VPN tunnels, hardware identity, CPU topology, pending package
// updates (ADR-0015, extended by ADR-0016/0017) — that doesn't fit Metric
// (not a time series) or Event (not a discrete occurrence). Resent in
// full each time, like the capability manifest (ADR-0004): the hub always
// replaces its stored copy for (host_id, kind), never appends.
type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	ReportedAtMs  int64                  `protobuf:"varint,3,opt,name=reported_at_ms,json=reportedAtMs,proto3" json:"reported_at_ms,omitempty"`
	Schema        int32                  `protobuf:"varint,4,opt,name=schema,proto3" json:"schema,omitempty"`
	Items         []*InventoryItem       `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_proto_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{6}
}

func (x *Inventory) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Inventory) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Inventory) GetReportedAtMs() int64 {
	if x != nil {
		return x.ReportedAtMs
	}
	return 0
}

func (x *Inventory) GetSchema() int32 {
	if x != nil {
		return x.Schema
	}
	return 0
}

func (x *Inventory) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Batch is what an agent pushes to POST /v1/ingest: a mixed batch of
// metrics, events, log lines and inventories in one message (ADR-0008,
// extended by ADR-0015).
type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"` // ULID, for idempotency
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Events        []*Event               `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	LogLines      []*LogLine             `protobuf:"bytes,5,rep,name=log_lines,json=logLines,proto3" json:"log_lines,omitempty"`
	Inventories   []*Inventory           `protobuf:"bytes,6,rep,name=inventories,proto3" json:"inventories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_proto_ingest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{7}
}

func (x *Batch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *Batch) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Batch) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Batch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Batch) GetLogLines() []*LogLine {
	if x != nil {
		return x.LogLines
	}
	return nil
}

func (x *Batch) GetInventories() []*Inventory {
	if x != nil {
		return x.Inventories
	}
	return nil
}

// IngestResponse is the hub's reply: the last confirmed offset, and
// whether this specific batch was a duplicate the hub already had.
type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastOffset    string                 `protobuf:"bytes,1,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	Duplicate     bool                   `protobuf:"varint,2,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_proto_ingest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{8}
}

func (x *IngestResponse) GetLastOffset() string {
	if x != nil {
		return x.LastOffset
	}
	return ""
}

func (x *IngestResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

var File_proto_ingest_proto protoreflect.FileDescriptor

const file_proto_ingest_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ingest.proto\x12\vbitacora.v1\"\xe2\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x127\n" +
	"\x06labels\x18\x03 \x03(\v2\x1f.bitacora.v1.Metric.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\fEventSubject\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\"7\n" +
	"\x06LogRef\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\"\xd7\x03\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x13\n" +
	"\x05ts_ms\x18\x02 \x01(\x03R\x04tsMs\x12$\n" +
	"\x0ets_received_ms\x18\x03 \x01(\x03R\ftsReceivedMs\x12\x17\n" +
	"\ahost_id\x18\x04 \x01(\tR\x06hostId\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x123\n" +
	"\asubject\x18\t \x01(\v2\x19.bitacora.v1.EventSubjectR\asubject\x123\n" +
	"\x05attrs\x18\n" +
	" \x03(\v2\x1d.bitacora.v1.Event.AttrsEntryR\x05attrs\x12 \n" +
	"\vfingerprint\x18\v \x01(\tR\vfingerprint\x12.\n" +
	"\blog_refs\x18\f \x03(\v2\x13.bitacora.v1.LogRefR\alogRefs\x12\x16\n" +
	"\x06schema\x18\r \x01(\x05R\x06schema\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x01\n" +
	"\aLogLine\x12\x13\n" +
	"\x05ts_ms\x18\x01 \x01(\x03R\x04tsMs\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\tR\x06stream\x12*\n" +
	"\x11unit_or_container\x18\x05 \x01(\tR\x0funitOrContainer\x12\x14\n" +
	"\x05level\x18\x06 \x01(\tR\x05level\x12\x10\n" +
	"\x03pid\x18\a \x01(\x05R\x03pid\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\"\xaa\x01\n" +
	"\rInventoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12;\n" +
	"\x05attrs\x18\x03 \x03(\v2%.bitacora.v1.InventoryItem.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\tInventory\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12$\n" +
	"\x0ereported_at_ms\x18\x03 \x01(\x03R\freportedAtMs\x12\x16\n" +
	"\x06schema\x18\x04 \x01(\x05R\x06schema\x120\n" +
	"\x05items\x18\x05 \x03(\v2\x1a.bitacora.v1.InventoryItemR\x05items\"\x83\x02\n" +
	"\x05Batch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12-\n" +
	"\ametrics\x18\x03 \x03(\v2\x13.bitacora.v1.MetricR\ametrics\x12*\n" +
	"\x06events\x18\x04 \x03(\v2\x12.bitacora.v1.EventR\x06events\x121\n" +
	"\tlog_lines\x18\x05 \x03(\v2\x14.bitacora.v1.LogLineR\blogLines\x128\n" +
	"\vinventories\x18\x06 \x03(\v2\x16.bitacora.v1.InventoryR\vinventories\"O\n" +
	"\x0eIngestResponse\x12\x1f\n" +
	"\vlast_offset\x18\x01 \x01(\tR\n" +
	"lastOffset\x12\x1c\n" +
	"\tduplicate\x18\x02 \x01(\bR\tduplicateB3Z1github.com/bitacora-dev/bitacora/proto/bitacorapbb\x06proto3"

var (
	file_proto_ingest_proto_rawDescOnce sync.Once
	file_proto_ingest_proto_rawDescData []byte
)

func file_proto_ingest_proto_rawDescGZIP() []byte {
	file_proto_ingest_proto_rawDescOnce.Do(func() {
		file_proto_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ingest_proto_rawDesc), len(file_proto_ingest_proto_rawDesc)))
	})
	return file_proto_ingest_proto_rawDescData
}

var file_proto_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_ingest_proto_goTypes = []any{
	(*Metric)(nil),         // 0: bitacora.v1.Metric
	(*EventSubject)(nil),   // 1: bitacora.v1.EventSubject
	(*LogRef)(nil),         // 2: bitacora.v1.LogRef
	(*Event)(nil),          // 3: bitacora.v1.Event
	(*LogLine)(nil),        // 4: bitacora.v1.LogLine
	(*InventoryItem)(nil),  // 5: bitacora.v1.InventoryItem
	(*Inventory)(nil),      // 6: bitacora.v1.Inventory
	(*Batch)(nil),          // 7: bitacora.v1.Batch
	(*IngestResponse)(nil), // 8: bitacora.v1.IngestResponse
	nil,                    // 9: bitacora.v1.Metric.LabelsEntry
	nil,                    // 10: bitacora.v1.Event.AttrsEntry
	nil,                    // 11: bitacora.v1.InventoryItem.AttrsEntry
}
var file_proto_ingest_proto_depIdxs = []int32{
	9,  // 0: bitacora.v1.Metric.labels:type_name -> bitacora.v1.Metric.LabelsEntry
	1,  // 1: bitacora.v1.Event.subject:type_name -> bitacora.v1.EventSubject
	10, // 2: bitacora.v1.Event.attrs:type_name -> bitacora.v1.Event.AttrsEntry
	2,  // 3: bitacora.v1.Event.log_refs:type_name -> bitacora.v1.LogRef
	11, // 4: bitacora.v1.InventoryItem.attrs:type_name -> bitacora.v1.InventoryItem.AttrsEntry
	5,  // 5: bitacora.v1.Inventory.items:type_name -> bitacora.v1.InventoryItem
	0,  // 6: bitacora.v1.Batch.metrics:type_name -> bitacora.v1.Metric
	3,  // 7: bitacora.v1.Batch.events:type_name -> bitacora.v1.Event
	4,  // 8: bitacora.v1.Batch.log_lines:type_name -> bitacora.v1.LogLine
	6,  // 9: bitacora.v1.Batch.inventories:type_name -> bitacora.v1.Inventory
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_ingest_proto_init() }
func file_proto_ingest_proto_init() {
	if File_proto_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ingest_proto_rawDesc), len(file_proto_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ingest_proto_goTypes,
		DependencyIndexes: file_proto_ingest_proto_depIdxs,
		MessageInfos:      file_proto_ingest_proto_msgTypes,
	}.Build()
	File_proto_ingest_proto = out.File
	file_proto_ingest_proto_goTypes = nil
	file_proto_ingest_proto_depIdxs = nil
}
